### ISSUE TITLE
@ngx-starter-kit/ngx-utils removed from npm

### ISSUE THREAD

**Issue by notarnet** [xmlking/ngx-starter-kit#156]
The npm package @ngx-starter-kit/ngx-utils does not exist anymore.
Can you restore npm package please?

**Comment by xmlking** [comment]
sorry I was aggregating my multiple npm accounts into single `org` account today.  
I had to delete  ngx-starter-kit account before adding it back as scope under my main account. 
now `@xmlking`, `@ngx-starter-kit` scopes are under single account. 
Will publish missing packages back ASAP.

**Comment by xmlking** [comment]
it should be UP now.  
let me know if you  need any other  lib packages under `@ngx-starter-kit/...`

**Comment by notarnet** [comment]
It's Ok. 
Thanks

**Comment by GianlucaMaggio** [comment]
Please re-publish also 0.0.3 version. We have a dependency on that version because we maintain all the previous version of our software and the latest one (0.0.7) is not compatible with angular 7.2.6.

Anyway consider that removing something from npm is considered a bad practice because people can depend on any version published (https://docs.npmjs.com/cli/unpublish).

Thanks
